stages:
  - build
  - publish

build:
  stage: build
  tags:
    - docker
  image: centos:7
  variables:
    BUNDLE_VERSION: "1.10.3-16-g3245f67"

  before_script:
    - echo "Using tarantool-enterprise-bundle ${BUNDLE_VERSION}"
    - curl -O -L https://tarantool:${DOWNLOAD_TOKEN}@download.tarantool.io/enterprise/tarantool-enterprise-bundle-${BUNDLE_VERSION}.tar.gz
    - tar -xzf tarantool-enterprise-bundle-${BUNDLE_VERSION}.tar.gz
    - rm -rf tarantool-enterprise-bundle-${BUNDLE_VERSION}.tar.gz
    - export PATH=$PWD/tarantool-enterprise:$PATH
    - yum -y install git gcc make unzip which
    - tarantoolctl rocks install ldoc --server=http://rocks.moonscript.org
    - export PATH=.rocks/bin:$PATH
  script:
    - tarantoolctl rocks make
    - ./test.lua
    - ./release.sh
    - make doc
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - doc/
      - release/
      - release-doc/

publish:
  stage: publish
  dependencies:
    - build
  tags:
    - shell
  when: manual
  only:
    - tags
  script:
    - aws --endpoint-url "${AWS_S3_ENDPOINT_URL}" s3 cp release/*.all.rock "s3://packages/rocks/"
    - aws --endpoint-url "${AWS_S3_ENDPOINT_URL}" s3 cp --recursive release-doc/ "s3://packages/rocks-doc/"
