test:
  stage: test
  tags:
    - docker
  image: tarantool/tarantool:1

  before_script:
    - apk add --no-cache git make ldoc
  script:
    - tarantoolctl rocks make
    - ./test.lua
  artifacts:
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - doc/
