language: minimal

services:
  - docker

install: docker-compose build test
script:
  - docker-compose run --rm test
after_success:
  - docker-compose build coverage
  - docker-compose run --rm coverage
after_script: docker-compose down
