language: minimal

services:
  - docker

before_install:
  - docker pull tarantool/tarantool:1.x-centos7

script:
  docker run -v `pwd`:/errors tarantool/tarantool:1.x-centos7  /bin/bash -c "cd /errors; tarantool /errors/taptest.lua;"
